name = "armadillo_jll"
uuid = "0631256a-41da-5d69-bb72-795e0d5510ec"
version = "9.800.3+0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
OpenBLAS_jll = "4536629a-c528-5b80-bd46-f80d51c5b363"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.0"
